title: Stackbit Exto Theme
baseURL: /
params:
  accent_color: blue
  color_scheme: dark
  footer:
    content: '&copy; Stackbit-Exto. All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    title: test theme
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
